name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        python-version: [3.9, 3.11, pypy-2.7, pypy-3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage mock pytest pytest-cov
      - name: Run tests
        run: pytest --cov=notify_send notify_send_tests.py
      - name: Run linting checks
        run: flake8 --ignore=E402,W504 --max-line-length=100 notify_send.py notify_send_tests.py
      - name: Report coveralls status
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.11'
        uses: AndreMiras/coveralls-python-action@develop
